### ISSUE TITLE
app getting null in applifecylestate like on resume and other 

### ISSUE THREAD

**Issue by lavahasif** [samuelezedi/flutter_clipboard#2]
): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'text' was called on null.
E/flutter (14312): Receiver: null
E/flutter (14312): Tried calling: text
E/flutter (14312): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter (14312): #1      FlutterClipboard.paste (package:clipboard/clipboard.dart:21:17)

**Comment by sahmadreza** [comment]
I have the same problem **just in android 10** .

**Comment by samuelezedi** [comment]
If it's getting null, then nothing was copied, don't you think? It means there's nothing on the clipboard

**Comment by yy1300326388** [comment]
First of all, I make sure that there is content in the clipboard, and secondly, when I switch applications back and forth several times, I get this error

**Comment by yy1300326388** [comment]
@lavahasif @lavahasif @sahmadreza  I found the answer https://github.com/flutter/flutter/issues/44267#issuecomment-569215719

**Comment by yy1300326388** [comment]
```
Future.delayed(Duration(milliseconds: 500)).then((_) => ..);
```

**Comment by lavahasif** [comment]
@yy1300326388  thank you . i just create android platform channel to overcome this error.thank you

**Comment by okbye123** [comment]
Try this https://www.youtube.com/watch?v=uz43VmWWlkc
